pipeline:
  test-commit-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean deploy -f cnj-config-backend-test/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles commit-stage
  javaee-commit-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean deploy -f cnj-config-backend-javaee/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles commit-stage
  javaee-dockerize-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean install -f cnj-config-backend-javaee/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles dockerize-stage -Dtest.target.route=http://10.118.17.191:8080
  javaee-integration-test-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean verify -f cnj-config-backend-javaee/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles integration-test-stage -Dtest.target.route=http://k8sapps.at.automotive.msg.team/cnj-config-backend-javaee
  micro-commit-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean deploy -f cnj-config-backend-micro/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles commit-stage
  micro-dockerize-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean install -f cnj-config-backend-micro/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles dockerize-stage -Dtest.target.route=http://10.118.17.191:8080
  micro-integration-test-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean verify -f cnj-config-backend-micro/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles integration-test-stage -Dtest.target.route=http://k8sapps.at.automotive.msg.team/cnj-config-backend-micro
  spring-commit-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean deploy -f cnj-config-backend-spring/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles commit-stage
  spring-dockerize-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean install -f cnj-config-backend-spring/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles dockerize-stage -Dtest.target.route=http://10.118.17.191:8080
  spring-integration-test-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean verify -f cnj-config-backend-spring/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles integration-test-stage -Dtest.target.route=http://k8sapps.at.automotive.msg.team/cnj-config-backend-spring
  notification-stage:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: drone
    when:
      status: [ success, failure ]

    